import styles from '../styles/About.module.scss'
import Image from 'next/image'
import Link from 'next/link'
import Head from 'next/head'
import { useKBar } from 'kbar'
import MenuButton from '../components/menuButton'

export default function About() {
const { query } = useKBar();
  return (
    <div className={styles.container}>
    <Head>
            <title>Toby B / About</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="./icon.png" />
      <meta name="theme-color" content="#fff" />
      <meta property="og:url" content="https://personal-sitev2.vercel.app" />
      <meta property="og:type" content="Personal website." />
      <meta
        property="og:title"
        content="Toby B." />
      <meta name="twitter:card" content="13 y/o full stack web dev & designer." />
      <meta
        property="og:description"
        content="About Toby." />
      <meta property="og:image" content={"/banner.png"} />
    </Head>
    <MenuButton></MenuButton>
    <body>
      <h1 className={styles.title}>About.</h1>
      <h2 className={styles.subtitle}>A small paragraph about me.</h2>
      
          <article>
            <div className={styles.aboutMe}>
              <p>
            Hi, I&apos;m Toby. I&apos;m a 13 year old full
            stack web developer from the UK.
            I&apos;m interested in everything to do
            with tech, from programming to
            building computers.
              </p>
              <p>
            I started programming when I was only
            7 years old, and I built my first computer
            at 10 years old. Over the past few
            years, I&apos;ve become more and more
            interested in all sorts of different projects,
            tools and languages!
              </p>
              <p>
            Recently, I&apos;ve been really interested in
            open source programming and I&apos;ve been
            helping loads of people with their own projects,
            and I&apos;d love to try and help you with yours.
            So, <a className={styles.contactRef} onClick={contactMe}>lets talk</a>.
              </p>
            </div>
          </article>
    </body>
    </div>
  );
}

function contactMe() {
  window.open("mailto:mail.toby@icloud.com", "_blank");
}