import styles from '../styles/Projects.module.scss'
import Head from 'next/head'
import { signIn } from "next-auth/react"
import prisma from '../utils/prisma';
import Guestbook from '../components/guestbook';

export default function GuestbookPage({ fallbackData }) {
  return (
    <>
    <div className={styles.container}>
    <Head>
    <title>Toby B / Guestbook</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="./icon.png" />
      <meta name="theme-color" content="#fff" />
      <meta property="og:url" content="https://personal-sitev2.vercel.app" />
      <meta property="og:type" content="Personal website." />
      <meta
        property="og:title"
        content="Toby B." />
      <meta name="twitter:card" content="13 y/o full stack web dev & designer." />
      <meta
        property="og:description"
        content="Toby's blog." />
      <meta property="og:image" content={"/banner.png"} />
    </Head>
    <body>

    <h1 className={styles.title}>Guestbook.</h1>
    <h1 className={styles.subtitle}>Leave feedback, a joke or some advice! Everything is read by me, and any comments are appreciated!</h1>

</body>
<>
<Guestbook fallbackData={fallbackData} />
</>
</div>
</>
  )
}

export async function getStaticProps() {
  const entries = await prisma.guestbook.findMany({
    orderBy: {
      updated_at: 'desc',
    },
  });

  const fallbackData = entries.map((entry) => ({
    id: entry.id.toString(),
    body: entry.body,
    created_by: entry.created_by.toString(),
    updated_at: entry.updated_at.toString()
  }));

  return {
    props: {
      fallbackData
    },
    revalidate: 60
  };
}

// Heavily inspired by Leerob! (leerob.io).