import styles from '../styles/Projects.module.scss'
import Image from 'next/image'
import Link from 'next/link'
import Head from 'next/head'
import { useKBar } from 'kbar'


export default function Projects() {
  return (
    <div className={styles.container}>
    <Head>
    <title>Toby B / Projects</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="./icon.png" />
      <meta property="og:url" content="https://personal-sitev2.vercel.app" />
      <meta property="og:type" content="Personal website." />
      <meta
        property="og:title"
        content="Toby B." />
      <meta name="twitter:card" content="13 y/o full stack web dev & designer." />
      <meta
        property="og:description"
        content="13 y/o full stack web dev & designer." />
      <meta property="og:image" content={"../public/preview.svg"} />
    </Head>
    <body>

    <h1 className={styles.title}>Projects.</h1>
    <h1 className={styles.subtitle}> To see all of my projects, check out my <a className={styles.gitRef} onClick={githubRef}>GitHub</a>!</h1>

    <div className={styles.homeadvisorContatiner}>
      <Image className={styles.HAimg} src="/homeAdv.svg" alt="Home Advisor" height= "500" width="500"/>
      <h1 className={styles.HAtitle}>Home advisor</h1>
      <p className={styles.HAdesc}>Home advisor is the perfect way 
      for students to find a home.</p>
    </div>

    <div className={styles.posstartContatiner}>
    <Image className={styles.PSimg} src="/ps.svg" alt="Positive Start" height= "500" width="500"/>
      <h1 className={styles.PStitle}>Positive start</h1>
      <p className={styles.PSdesc}>Positive start is an email newsletter that <br /> helps you look fowards to waking up.</p>
    </div>
</body>
</div>
    )
}

function githubRef() {
  window.open("https://github.com/itstobez?tab=repositories", "_blank");
}
